[dependencies.conjuration]
path = "../.."

[dependencies.draco]
github = "guitsaru/draco"

[dependencies.frame-timer]
github = "Nitemaeric/dr-frame-timer"
branch = "fix/graph-initial-contents"
entrypoint = "frame-timer.rb"
