[dependencies.conjuration]
path = "../../lib"
entrypoint = "conjuration.rb"

[dependencies.frame-timer]
github = "owenbutler/dr-frame-timer"
entrypoint = "frame-timer.rb"

[dependencies.dragon_input]
github = "Nitemaeric/dragon_input"
